version: '3'
services:
  driver:
    image: jeguzzi/robomaster_ros:galactic
    build:
      context: ..
      dockerfile: Dockerfile
    network_mode: host
    pid: host
    ipc: host
    command: ros2 launch robomaster_ros s1.launch name:=rm_s1
  teleop:
    privileged: true
    image: jeguzzi/robomaster_ros:galactic
    network_mode: host
    pid: host
    ipc: host
    command: ros2 launch robomaster_ros teleop.launch model:=s1 name:=rm_s1
